In [47]:
import numpy as np

In [48]:
a= np.array([[1,2,3],[3,4,5]])

In [49]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [50]:
a[1]

array([3, 4, 5])

In [51]:
b=np.array([1,2,3,4,5,6])

In [52]:
b

array([1, 2, 3, 4, 5, 6])

In [53]:
b[2]

3

In [54]:
b[2:]

array([3, 4, 5, 6])

In [55]:
a[4:]

array([], shape=(0, 3), dtype=int64)

In [56]:
a[1:]

array([[3, 4, 5]])

In [57]:
b[2:]

array([3, 4, 5, 6])

In [58]:
b[3:]

array([4, 5, 6])

In [59]:
a = np.array(23)

In [60]:
print("no of dimensions",a.ndim)
print("shape of array" , a.shape)
print("len of shape", len(a.shape))
print('size',a.size)

no of dimensions 0
shape of array ()
len of shape 0
size 1


In [61]:
a = np.array([[23,34],[34,35]])
print("no of dimensions",a.ndim)
print("shape of array" , a.shape)
print("len of shape", len(a.shape))
print('size',a.size)

no of dimensions 2
shape of array (2, 2)
len of shape 2
size 4


In [62]:
a = np.array([[[1,2,4],[1,2,6]],[[1,2,5],[1,2,4]]])
print("no of dimensions",a.ndim)
print("shape of array" , a.shape)
print("len of shape", len(a.shape))
print('size',a.size)

no of dimensions 3
shape of array (2, 2, 3)
len of shape 3
size 12


In [63]:
a = np.array([[
                [[1,2,4],
                 [1,2,6]],
              [[1,2,5],
               [1,2,4]]
               ]
               ,
              [
                  [[2,3,4],
                   [3,4,5]],
                  [[1,2,5],
                   [1,2,4]]
              ]
            
              
             ])
print("no of dimensions",a.ndim)
print("shape of array" , a.shape)
print("len of shape", len(a.shape))
print('size',a.size)

no of dimensions 4
shape of array (2, 2, 2, 3)
len of shape 4
size 24


In [64]:
np.zeros(2)

array([0., 0.])

In [65]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
b=np.zeros((2,3,4))
b
b.shape
len(b.shape)

3

In [67]:
np.empty(3)

array([3., 2., 1.])

In [68]:
np.array((3,4,5))

array([3, 4, 5])

In [69]:
np.arrange(2,10,1)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
np.arange(2,10,1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=np.array([2,3,4,1,6,7,9,8])


In [ ]:
arr

array([2, 3, 4, 1, 6, 7, 9, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [ ]:
names=np.array(['abhi','ridham','naresh'])
ages=np.array([29,25,34])

indices=np.lexsort((names,ages))

In [ ]:
print(names[indices])

['ridham' 'abhi' 'naresh']


In [ ]:
print(ages[indices])

[25 29 34]


In [ ]:
arr=np.array([24,56,13,76,89,98,90])
np.partition(arr,2)

array([13, 24, 56, 76, 89, 98, 90])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
z=np.array([[6,7]])
print(x.shape)
np.concatenate((x,y,z),axis=0)

(2, 2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [6, 7]])

In [ ]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.reshape(arr,(2,3),order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
arr=np.array([89,23,101])
arr

array([ 89,  23, 101])

In [ ]:
arr[2:]

array([101])

In [ ]:
arr[-1:]

array([101])

In [ ]:
arr[-2:]

array([ 23, 101])

In [ ]:
arr[-3]

89

In [ ]:
arr[-3:] 

array([ 89,  23, 101])

In [ ]:
arr[:-1] 

array([89, 23])

In [ ]:
a=np.array([[[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]],
           [[4,5,6,9],
             [1,2,3,4],
             [5,6,7,8],
            ],
            [[4,5,6,9],
             [1,2,3,4],
             [5,6,7,8],
            ]]
           )

In [ ]:
a.ndim

3

In [ ]:
print(a<6)

[[[ True  True  True  True]
  [ True False False False]
  [False False False False]]

 [[ True  True False False]
  [ True  True  True  True]
  [ True False False False]]

 [[ True  True False False]
  [ True  True  True  True]
  [ True False False False]]]


In [ ]:
a[a<4]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a=np.array([[13,45,32,2],[75,65,32,99],[54,56,23,76]])

In [ ]:
a

array([[13, 45, 32,  2],
       [75, 65, 32, 99],
       [54, 56, 23, 76]])

In [ ]:
a[a<7]

array([2])

In [ ]:
a[(a<7) | (a>45)]

array([ 2, 75, 65, 99, 54, 56, 76])

In [ ]:
np.nonzero((a<7) | (a>45))

(array([0, 1, 1, 1, 2, 2, 2]), array([3, 0, 1, 3, 0, 1, 3]))

In [ ]:
a=np.arange(1,25).reshape(2,12)

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(a ,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
a=np.arange(20)
b=np.arange(5,25)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
a.sum()

190

In [ ]:
a+b

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43])

In [ ]:
a=np.arange(1,10).reshape(3,3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b=a.sum(axis=0)
b

array([12, 15, 18])

In [ ]:
c=a.sum(axis=1)
c

array([ 6, 15, 24])

In [ ]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b=a.transpose()
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a=np.arange(4,10).reshape(2,3)
a

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
c=a.T
c

array([[4, 7],
       [5, 8],
       [6, 9]])

In [ ]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim

2

In [ ]:
revr=np.flip(arr)

In [ ]:
revr

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])